#!/bin/sh
git --work-tree=/home/warsong/public/micrometreuk --git-dir=/home/warsong/hooks/micrometreuk.git checkout -f
cd ~/public/micrometreuk
rm -rf .jekyll-cache
docker-compose stop
docker-compose start
exit
