#!/bin/sh
echo "Deploying master branch to production..."
git --work-tree=/home/injera/public/micrometreuk --git-dir=/home/injera/hooks/micrometreuk.git checkout -f
cd ~/public/micrometreuk
docker-compose stop
docker-compose start
echo "Successfully deployed master branch ."

exit
