title: Micrometreuk
email: info@micrometre.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  Automating build environment.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed


header_pages:
  - testi.md
  - hosting.md
  - services.md
  - learn.md
  - contact.md
  - privacy.md
show_excerpts: true

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
